### ISSUE TITLE
error after collapsing samples

### ISSUE THREAD

**Issue by LisaBlazek** [jradrion/TEFLoN#10]
hello!
i wanted to test teflon on some sequencing data of mine!
after finishing collapsing the samples i get following error:

```
Traceback (most recent call last):
  File "/software/TEFLoN/TEFLoN_env/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
error concatenating positions
```
this is the command i'm using

`python /software/TEFLoN/teflon_collapse.py -wd /project/TEFLoN -d /project/TEFLoN/ref.prep_TF/ -s /project/TEFLoN/samples.txt -es /software/BIN/samtools -n1 5 -n2 5 -q 15 -t 19
`

i'm only a beginner at python, so im not really sure what to do now.
it would be great if you could help me out!

kind regards, 
lisa

**Comment by virginiascarlett** [comment]
I also have this issue. I am running TEFLoN on a cluster using the SLURM batch system. I am working in a conda environment with samtools=1.9 bwa=0.7.17 python=2.7. Here is the command I used:
```
python /global/projectb/sandbox/plant/hybridum/software/TEFLoN/teflon_collapse.py \
    -wd $MYCWD \
    -d $MYCWD/BhABR113ref.prep_TF \
    -s $MYCWD/samples.txt \
    -es /global/projectb/sandbox/plant/hybridum/software/my_TEFLoN_env/bin/samtools \
    -n1 1 \
    -n2 2 \
    -q 18 \
    -t 32
```

Here is my error message from standard out:
```
Subsampling to the minimum read depth from a single sample: 51.0
finished standardaizing sample depth
creating directory: /global/projectb/scratch/vstartag/jacob_internship/Bhybridum/countPos

finished collapsing samples
error concatenating positions
```
Here is the top and bottom of the standard error output:
```
Process Process-56:
Traceback (most recent call last):
Process Process-37:
Process Process-40:
  File "/global/projectb/sandbox/plant/hybridum/software/my_TEFLoN_env/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
Traceback (most recent call last):
Traceback (most recent call last):
  File "/global/projectb/sandbox/plant/hybridum/software/my_TEFLoN_env/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
  File "/global/projectb/sandbox/plant/hybridum/software/my_TEFLoN_env/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
Process Process-62:
Traceback (most recent call last):
Process Process-42:
.
.
.
  File "/global/projectb/sandbox/plant/hybridum/software/TEFLoN/teflon_collapse.py", line 49, in worker1
  File "/global/projectb/sandbox/plant/hybridum/software/TEFLoN/teflon_collapse.py", line 49, in worker1
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "/global/projectb/sandbox/plant/hybridum/software/TEFLoN/teflon_collapse.py", line 49, in worker1
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "/global/projectb/sandbox/plant/hybridum/software/TEFLoN/teflon_collapse.py", line 49, in worker1
  File "/global/projectb/sandbox/plant/hybridum/software/TEFLoN/teflon_collapse.py", line 49, in worker1
  File "/global/projectb/sandbox/plant/hybridum/software/TEFLoN/teflon_collapse.py", line 49, in worker1
  File "/global/projectb/sandbox/plant/hybridum/software/TEFLoN/teflon_collapse.py", line 49, in worker1
  File "/global/projectb/sandbox/plant/hybridum/software/TEFLoN/teflon_collapse.py", line 49, in worker1
  File "/global/projectb/sandbox/plant/hybridum/software/TEFLoN/teflon_collapse.py", line 49, in worker1

```

**Comment by virginiascarlett** [comment]
A little more info. I tried running teflon_collapse.py on a single core and got a slightly different error. (--ntasks= 1and --cpus-per-task=1 on our SLURM batch system.)

Here is the entire standard error:
`Process Process-2:`

Here is the top and bottom of standard out:
```
Subsampling to the minimum read depth from a single sample: 51.0
Creating /global/projectb/scratch/vstartag/jacob_internship/Bhybridum/Bhybridum1.sorted.subsmpl.bam
cmd: /global/projectb/sandbox/plant/hybridum/software/my_TEFLoN_env/bin/samtools view -b -s 0.515 /global/projectb/scratch/vstartag/jacob_internship/Bhybridum/Bhybridum1.sorted.bam
cmd: /global/projectb/sandbox/plant/hybridum/software/my_TEFLoN_env/bin/samtools index /global/projectb/scratch/vstartag/jacob_internship/Bhybridum/Bhybridum1.sorted.subsmpl.bam
Calculating alignment statistics for /global/projectb/scratch/vstartag/jacob_internship/Bhybridum/Bhybridum1.sorted.subsmpl.bam
cmd: /global/projectb/sandbox/plant/hybridum/software/my_TEFLoN_env/bin/samtools stats -t /global/projectb/scratch/vstartag/jacob_internship/Bhybridum/BhABR113ref.prep_TF/BhABR113ref.genomeSize.txt /global/projectb/scratch/vstartag/jacob_internship/Bhybridum/Bhybridum1.sorted.subsmpl.bam
cmd: /global/projectb/sandbox/plant/hybridum/software/my_TEFLoN_env/bin/samtools depth -Q 18 /global/projectb/scratch/vstartag/jacob_internship/Bhybridum/Bhybridum1.sorted.subsmpl.bam | awk '{sum+=$3; sumsq+=$3*$3} END {print "Average = ",sum/NR; print "Stdev = ",sqrt(sumsq/NR - (sum/NR)**2)}' > /global/projectb/scratch/vstartag/jacob_internship/Bhybridum/Bhybridum1.sorted.subsmpl.cov.txt
Creating /global/projectb/scratch/vstartag/jacob_internship/Bhybridum/Bhybridum2.sorted.subsmpl.bam
.
.
.
Calculating alignment statistics for /global/projectb/scratch/vstartag/jacob_internship/Bhybridum/Bhybridum19.sorted.subsmpl.bam
cmd: /global/projectb/sandbox/plant/hybridum/software/my_TEFLoN_env/bin/samtools stats -t /global/projectb/scratch/vstartag/jacob_internship/Bhybridum/BhABR113ref.prep_TF/BhABR113ref.genomeSize.txt /global/projectb/scratch/vstartag/jacob_internship/Bhybridum/Bhybridum19.sorted.subsmpl.bam
cmd: /global/projectb/sandbox/plant/hybridum/software/my_TEFLoN_env/bin/samtools depth -Q 18 /global/projectb/scratch/vstartag/jacob_internship/Bhybridum/Bhybridum19.sorted.subsmpl.bam | awk '{sum+=$3; sumsq+=$3*$3} END {print "Average = ",sum/NR; print "Stdev = ",sqrt(sumsq/NR - (sum/NR)**2)}' > /global/projectb/scratch/vstartag/jacob_internship/Bhybridum/Bhybridum19.sorted.subsmpl.cov.txt
Creating /global/projectb/scratch/vstartag/jacob_internship/Bhybridum/Bhybridum20.sorted.subsmpl.bam
cmd: /global/projectb/sandbox/plant/hybridum/software/my_TEFLoN_env/bin/samtools view -b -s 0.699 /global/projectb/scratch/vstartag/jacob_internship/Bhybridum/Bhybridum20.sorted.bam
cmd: /global/projectb/sandbox/plant/hybridum/software/my_TEFLoN_env/bin/samtools index /global/projectb/scratch/vstartag/jacob_infinished standardaizing sample depth

finished collapsing samples
error concatenating positions
```

Note I have 24 samples in samples.txt, but the script seems to have decided it was "finished collapsing samples" part way through sample #20?

**Comment by AlexandreDup** [comment]
hello!

I'm here for the same problem, I wanted to try TEFLoN (on SLURM cluster) on my own sequencing data and after finishing collapsing the samples, i get the same error:

Traceback (most recent call last):
  File "/tools/python/2.7.15/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
error concatenating positions

Has anyone found a solution ? I tried on the data provided on the github and that works, so... I don't really understand why that doesn't on my own data 

best regards,
AlexandreDup
